---
- name: Local addons playbook (compute) 
  hosts: compute
  roles:
  - { role: ansible-role-sacct_gpu, tags: ['local','gpu'] }
  - { role: ansible-role-slurm-spank-gpu, tags: ['local', 'gpu', 'spank'] }
  - { role: local-customization, tags: ['local'] }
