---

- name: Local customization

  hosts: production
  gather_facts: no
  strategy: free
# strategy: debug
  remote_user: root
  become: yes

- hosts: install
  roles:
  - local-customization-install

- hosts: admin
  roles:
  - local-customization-admin
  
- hosts: login
  remote_user: root
  roles:
  - { role: local-customization-login, tags: [ 'login' ] }

- hosts: gpu
  roles:
  - { role: local-customization-gpu, tags: [ 'gpu' ] }

- hosts: nfs
  roles:
  - { role: local-customization-nfs, tags: [ 'nfs' ] }

- hosts: all
  roles:
#- { role: ansible-role-firmware-updates, tags: [ 'fw' ], when: ansible_virtualization_role != "guest" }
  - { role: ansible-role-firmware-updates, tags: [ 'fw' ] }
  - { role: ansible-role-serial-console-root, when: ansible_virtualization_role != "guest" }
  - { role: local-customization }


