---

- name: Local customization
  hosts: production
  strategy: free
# strategy: debug
  remote_user: root
  become: yes


- hosts: all
  roles:
  - { role: ansible-role-firmware-updates, when: ansible_virtualization_role != "guest" }
  - { role: ansible-role-serial-console-root, when: ansible_virtualization_role != "guest" }
  - local-customization

- hosts: install
  roles:
  - local-customization-install

- hosts: admin
  roles:
  - local-customization-admin
  
- hosts: login
  remote_user: root
  roles:
  - local-customization-login

- hosts: nfs
  roles:
  - local-customization-nfs

