---
# ansible-playbook file: local-customization.yml
#

- hosts: all
  roles:
  - local-customization
  - { role: local-bios-updates, when: ansible_virtualization_role == 'host' }

- hosts: admin
  roles: 
  - local-customization-admin

- hosts: install
  roles:
  - local-customization-install

- hosts: nfs
  roles:
  - local-customization-nfs

#- hosts: compute
#  roles:
#  - local-customization-compute
