---

- hosts: install
  roles:
  - local-customization-install

- hosts: all
  roles:
  - { role: local-bios-updates, when ansible_virtualization_role == 'host' }
  - local-customization

- hosts: admin
  roles:
  - local-customization-admin
  
#- hosts: nfs
#  roles:
#  - local-customization-nfs

