---

- hosts: all
  roles:
  - { role: ansible-role-firmware-updates, tags: [ 'bios', 'IB' ], when ansible_virtualization_role == 'host' }
  - { role: ansible-role-serial-console-root, when ansible_virtualization_role == 'host' }
  - local-customization

- hosts: install
  roles:
  - local-customization-install

- hosts: admin
  roles:
  - local-customization-admin
  
- hosts: login
  roles:
  - local-customization-login

#- hosts: nfs
#  roles:
#  - local-customization-nfs

