# ansible-playbook file: site.yml
#

# Warning: there are a few steps in between the following roles that still need to be carried out manually.
#           This playbook is more, at this point, a guideline for the proper deployment sequence 

- import_playbook: admin.yml
#- import_playbook: provisioning.yml
- import_playbook: install.yml
#- import_playbook: tools/reinstall_node.yml
- import_playbook: nfs.yml
- import_playbook: login.yml
#- import_playbook: tools/reinstall_computes.yml
- import_playbook: compute.yml
- import_playbook: grid.yml
