---
# tasks file for ansible-role-postfix
#
- name: make sure postfix is installed
  package: name=postfix state=present

- name: Create the postfix main.cf config file
  template: src=main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode="0644" backup=yes
  notify: restart postfix

- name: Start and enable postfix
  service: name=postfix state=started enabled=yes

