---
# tasks file for ansible-role-postfix
#
- name: make sure postfix is installed
  tags: postfix
  action: >
    {{ ansible_pkg_mgr }}
    name=postfix
    state=installed

- name: Lets tag main.cf to ansible
  tags: postfix
  lineinfile: dest=/etc/postfix/main.cf
              line="# This file is {{ ansible_managed }} "
              state=present
              regexp="^# This file is .*$"
              backup=yes

- name: Lets listen to internal interface
  tags: postfix
  lineinfile: dest=/etc/postfix/main.cf 
              line="inet_interfaces = localhost, {{ int_ip_addr }}" 
              backup=yes 
              regexp="^inet_interfaces =.*$"
              state=present
  notify:
    - reload postfix

- name: Lets masquerade mail from internal hosts
  tags: postfix
  lineinfile: dest=/etc/postfix/main.cf
              line="masquerade_domains = {{ intDomain }}, localdomain"
              backup=yes 
              regexp="^masquerade =.*$"
              state=present

  #when: postfix_relayhost == "{{ inventory_hostname }}" 
  notify:
    - reload postfix

# inet_interfaces = localhost

