---

internal_interface: "em3" 
external_interface: "em4"

network_ether_interfaces:
  - device: "{{external_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{ext_ip_addr}}"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    defroute: "yes"
    nm_controlled: "no"
    type: "Ethernet"

  - device: "{{internal_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{int_ip_addr}}"
    netmask: "{{int_net_mask}}"
    gateway: "{{int_gateway}}"
    defroute: "no"
    nm_controlled: "no"
    type: "Ethernet"

limits_domains:
  - domain: '500:65535'
    type: '-'
    item: nproc
    value: 128
