---
# Tasks for compute-node

- name: Copy new BIOS upgrade to /tmp
  tags: firmware
  copy: src=files/Dell/{{ bios_update_name }} mode=0755 dest=/tmp
  notify: Install update
  when: (ansible_bios_version != "2.2.5")
