---

internal_interface: "em1"
ib_interface: "ib0"

#ib_ip_addr: "10.2.3.12"
ib_net_mask: "255.255.0.0"

network_ether_interfaces:
  - device: "{{ib_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{ib_ip_addr}}"
    netmask: "{{ib_net_mask}}"
    nm_controlled: "no"

  - device: "{{internal_interface}}"
    bootproto: "dhcp"
    onboot: "yes"
    nm_controlled: "no"
    type: "Ethernet"

networks:
  - "network --onboot=yes --bootproto=dhcp --device={{ internal_interface }} --noipv6"

infiniband_available: True
#rdma_configure_single_port: True
rdma_configure_single_port: False
rdma_manage_rdma: False
rdma_manage_opensm: False

# 
install_ssh_host_keys_to_nfs: True
yum_repos:
  - { name: "Mellanox-IB", description: "Mellanox IB-stack repo", url: "http://{{ kickstart_server_ip }}/Mellanox-repo/{{ ansible_distribution_major_version }}", gpgcheck: no, enabled: yes }

## PXE

kickstart_profile: FGCI-nfs-node
#kickstart_server_ip: "{{kickstart_server_ip}}"
kickstart_partitions: |
  bootloader --location=mbr --driveorder=sda,sdb --append="selinux=0"
  zerombr
  clearpart --initlabel --drives=sda,sdb --all
  part raid.01 --size=500 --asprimary --ondrive=sda 
  part raid.02 --size=500 --ondrive=sdb
  part raid.11 --size=1 --grow --asprimary --ondrive=sda
  part raid.12 --size=1 --grow --ondrive=sdb
  raid /boot --level=RAID1 --fstype=ext3 --device=md0 raid.01 raid.02
  raid pv.01 --fstype="lvmpv" --device md1 --level=RAID1 raid.11 raid.12
  volgroup vgroot --pesize=4096 pv.01
  logvol /  --fstype="xfs" --size=200000 --name=lv_root --vgname=vgroot
  logvol swap --fstype="swap" --size=10000 --name=lv_swap --vgname=vgroot
  logvol /var  --fstype="xfs" --size=200000 --name=lv_var --vgname=vgroot
  logvol /tmp  --fstype="xfs" --size=100000 --name=lv_tmp --vgname=vgroot
#  part /scratch --fstype="xfs" --onpart=sdc
kickstart_packages: |
  epel-release
  git
  @infiniband
  infiniband-diags
  iperf
  mcelog
  netcdf
  nfs-utils
  nscd
  openssh-server
  smartmontools
  yum-plugin-fastestmirror

# NFS exports

nfs_exports: { "/home 10.0.0.0/8(rw,sync,no_root_squash)","/scratch 10.0.0.0/8(rw,no_root_squash)" }

# Configure smartd
smartd_service: True

unconfigured_packages:
  - bash-completion
  - bonnie++
  - cvs
  - epel-release
  - git
  - iperf
  - mcelog
  - net-tools
  - nfs-utils
  - nscd
  - openmpi
  - openssh-server
  - pdsh
  - pciutils
  - perl-Filesys-Df
  - time
  - wget
  - yum-plugin-fastestmirror
  - dstat

