---
# This playbook will make a backup of your Cluster's critical files
#
# TODO: 
# - create a dir name with embeded date
# - have maximum backup | delete old ones
# - bckpDir variable valid for all play
# - Add mySQL Slurm DB dumpping role

- hosts: localhost
  vars:
    - bckpDir: "backup"

  # Create backup folder
  tasks: 
    - name: Create a backup folder # Remember to add it to .gitingnore
      file: path={{ bckpDir }} state=directory mode=0755
      tags: preBackup

    - name: Make sure git ignores backup folder
      lineinfile: dest={{ inventory_dir }}/.gitignore state=present line="{{ bckpDir }}/"
      tags: preBackup

    - name: Check if hostcert.pem and hostkey.pem exists locally
      stat: path={{ inventory_dir }}/files/certificates/hostcert.pem
      stat: path={{ inventory_dir }}/files/certificates/hostkey.pem
      tags: preBackup

    - name: Check if munge.key exists locally
      stat: path={{ inventory_dir }}/files/munge.key
      tags: preBackup

    - name: Check if nodes dir exists locally
      stat: path={{ inventory_dir }}/files/nodes/{{ item }}
      with_items: 
        - "{{ groups['compute'] }}"
        - install
        - login
        - grid
        - nfs
      tags: preBackup

    # Backup Repo
    - name: compress repo into tarball and place it in backup folder
      shell: tar -zczf {{ bckpDir }}/fgci-ansible-{{ ansible_date_time.date }}.tar.gz .
      args:
        chdir: "{{ inventory_dir }}"

- hosts: install
  become: yes
  vars:
    - bckpDir: "backup"

  tasks:
    - name: Copy files from Install node
      fetch: src={{ item }} dest={{ inventory_dir }}/{{ bckpDir }} fail_on_missing=yes
      with_items:
        - /etc/slurm/slurm.conf
        # - Add log files here
     
- hosts: grid
  become: yes
  vars:
    - bckpDir: "backup"

  tasks:
    - name: Copy files from grid node
      fetch: src={{ item }} dest={{ inventory_dir }}/{{ bckpDir }} fail_on_missing=yes
      with_items:
        - /etc/arc.conf
        # - Add log files here

- hosts: install
  become: yes
  vars:
    - bckpDir: "backup"

  # LA: Still haven't tested what's bellow!! Needs some closer check and a free testing cluster to minimize possible damages - Waiting for Io to be empty.

  tasks:
    - name: stop slurmctld
      service: name=slurmctld state=stopped

    - name: stop slurmdbd
      service: name=slurmdbd state=stopped
      delegate_to: install

    - name: Dump Slurm DB
      mysql_db: state=dump name=all target=/tmp/{{ siteName }}-install-slurmDB.sql
      delegate_to: install

    - name: start slurmdbd
      service: name=slurmdbd state=started
      delegate_to: install

    - name: start slurmctld
      service: name=slurmctld state=started

    - name: Fetch Slurm DB dump file from install node
      fetch: src=/tmp/{{ siteName }}-install-slurmDB.sql dest={{ inventory_dir }}/{{ bckpDir }} fail_on_missing=yes


